package com.pignasoft.composemvisample.ui.theme
import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFB71E39)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDADA)
val light_onPrimaryContainer = Color(0xFF40000B)
val light_secondary = Color(0xFF765657)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDADA)
val light_onSecondaryContainer = Color(0xFF2C1516)
val light_tertiary = Color(0xFF76592F)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFDDB1)
val light_onTertiaryContainer = Color(0xFF291800)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A1A)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A1A)
val light_surfaceVariant = Color(0xFFF4DDDD)
val light_onSurfaceVariant = Color(0xFF524343)
val light_outline = Color(0xFF857373)
val light_inverseOnSurface = Color(0xFFFBEEED)
val light_inverseSurface = Color(0xFF362F2F)
val light_inversePrimary = Color(0xFFFFB3B5)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFFB71E39)

val dark_primary = Color(0xFFFFB3B5)
val dark_onPrimary = Color(0xFF680018)
val dark_primaryContainer = Color(0xFF920026)
val dark_onPrimaryContainer = Color(0xFFFFDADA)
val dark_secondary = Color(0xFFE6BDBD)
val dark_onSecondary = Color(0xFF44292A)
val dark_secondaryContainer = Color(0xFF5D3F40)
val dark_onSecondaryContainer = Color(0xFFFFDADA)
val dark_tertiary = Color(0xFFE6C18D)
val dark_onTertiary = Color(0xFF432C05)
val dark_tertiaryContainer = Color(0xFF5C421A)
val dark_onTertiaryContainer = Color(0xFFFFDDB1)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A1A)
val dark_onBackground = Color(0xFFECE0DF)
val dark_surface = Color(0xFF201A1A)
val dark_onSurface = Color(0xFFECE0DF)
val dark_surfaceVariant = Color(0xFF524343)
val dark_onSurfaceVariant = Color(0xFFD7C1C1)
val dark_outline = Color(0xFF9F8C8C)
val dark_inverseOnSurface = Color(0xFF201A1A)
val dark_inverseSurface = Color(0xFFECE0DF)
val dark_inversePrimary = Color(0xFFB71E39)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB3B5)


val seed = Color(0xFFB81F3A)
